-- Add issue reporting tables for global fault capture and admin triage.

create table if not exists public.issue_reports (
  id uuid primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  reporter_user_id uuid references public.employees(id) on delete set null,
  reporter_email text,
  reporter_name text,
  page_url text not null,
  route_path text not null,
  module_key text not null,
  notes text not null,
  severity text not null default 'medium' check (severity in ('low', 'medium', 'high', 'critical')),
  status text not null default 'new' check (status in ('new', 'investigating', 'solved', 'closed')),
  browser_context jsonb not null default '{}'::jsonb,
  has_screenshot boolean not null default false,
  has_console_log boolean not null default false,
  artifact_purge_after timestamp with time zone,
  solved_at timestamp with time zone,
  closed_at timestamp with time zone,
  assigned_to_user_id uuid references public.employees(id) on delete set null,
  last_status_changed_by uuid references public.employees(id) on delete set null
);

create table if not exists public.issue_report_artifacts (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.issue_reports(id) on delete cascade,
  artifact_type text not null check (artifact_type in ('screenshot', 'console_log')),
  storage_provider text not null,
  storage_bucket text not null,
  storage_key text not null,
  content_type text not null,
  byte_size bigint not null default 0,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone
);

create table if not exists public.issue_report_events (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.issue_reports(id) on delete cascade,
  actor_user_id uuid references public.employees(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists issue_reports_status_idx on public.issue_reports(status);
create index if not exists issue_reports_created_at_idx on public.issue_reports(created_at desc);
create index if not exists issue_reports_module_key_idx on public.issue_reports(module_key);
create index if not exists issue_reports_solved_at_idx on public.issue_reports(solved_at);
create index if not exists issue_reports_artifact_purge_after_idx on public.issue_reports(artifact_purge_after);
create index if not exists issue_report_artifacts_ticket_id_idx on public.issue_report_artifacts(ticket_id);
create index if not exists issue_report_artifacts_deleted_at_idx on public.issue_report_artifacts(deleted_at);
create index if not exists issue_report_events_ticket_id_idx on public.issue_report_events(ticket_id, created_at desc);
