import type { SupabaseClient } from '@supabase/supabase-js'
import type {
  PackagePaymentBreakdown,
  PackageResolvedSelection,
  TravelPackageFolder,
  TravelPackageQuote,
  TravelPackageReservation,
} from '@/app/types/packages'
import { recordPackageAuditEvent } from '@/lib/packageAudit'
import {
  buildPassengerSummary,
  getPackageDepositPaymentSummary,
  getPackageOfferDiscountTotal,
  getPackageQuoteDiscountType,
  normalizePackageQuotePayload,
  rebuildConvertedPackageSnapshotFromQuotes,
} from '@/lib/packageQuote'
import {
  buildPackageQuoteReservationDrafts,
  buildSharedGroupTransportDraft,
  type PackageQuoteReservationDraft,
  type PackageQuoteReservationFamily,
} from '@/lib/packageQuoteReservations'
import { syncPackagePaymentFinancials } from '@/lib/packagePaymentsServer'

type SyncConflict = {
  kind: 'invoice' | 'payment' | 'reservation' | 'group_member'
  message: string
  objectId?: string
}

export type PackageQuoteSyncResult = {
  packageId: string
  quoteIds: string[]
  status: 'synced' | 'review_required'
  createdReservations: number
  updatedReservations: number
  cancelledReservations: number
  updatedCredits: number
  createdPaymentRequests: number
  updatedPaymentRequests: number
  cancelledPaymentRequests: number
  conflicts: SyncConflict[]
  snapshot: TravelPackageFolder['selected_quote_snapshot']
}

export async function markPackageQuoteSyncFailed(
  supabase: SupabaseClient,
  packageId: string,
  error: unknown,
) {
  const { data } = await supabase
    .from('travel_packages')
    .select('metadata')
    .eq('id', packageId)
    .maybeSingle()
  const metadata = metadataOf(data?.metadata)
  await supabase
    .from('travel_packages')
    .update({
      metadata: {
        ...metadata,
        quoteSync: {
          status: 'failed',
          failedAt: new Date().toISOString(),
          message: error instanceof Error ? error.message : 'Package reconciliation failed',
        },
      },
    })
    .eq('id', packageId)
}

type ExistingReservation = TravelPackageReservation & {
  itemCount: number
}

type DesiredReservation = PackageQuoteReservationDraft & {
  quoteId: string | null
  groupMemberId: string | null
  familyLabel: string | null
  currency: string
  depositRequired: boolean
  depositAmount: number
}

type DesiredPaymentRequest = {
  quoteId: string
  groupMemberId: string | null
  familyLabel: string | null
  source: 'final_quote_deposit_request' | 'final_quote_payment_breakdown'
  paymentType: 'deposit' | 'payment'
  paymentMethod: 'cash' | 'bank_transfer' | 'card'
  amount: number
  currency: string
  notes: string
  metadata: Record<string, unknown>
}

const QUOTE_METADATA_KEYS = [
  'sourceKey',
  'syncKey',
  'familyLabel',
  'optionId',
  'flightPart',
  'linkedFlightSelection',
  'linkedFlightSelections',
  'stayGroupId',
  'stayGroupLabel',
  'addonOptions',
  'quantity',
  'visaPassengerCategory',
  'sharedGroupTransport',
  'billingAllocation',
  'physicalReservation',
  'includesZiyarat',
  'includesTourGuide',
  'transportRoutes',
  'transportMainSupplierId',
  'transportMainSupplierName',
  'transportNetCost',
  'transportNetCurrency',
  'familyAllocations',
  'adjustmentType',
  'quoteSoldPrice',
  'quoteDiscountTotal',
  'quoteInternalNotes',
] as const

const PROGRESSED_RESERVATION_STATUSES = new Set([
  'reserved',
  'deposit_required',
  'paid',
  'confirmed',
  'changed',
  'failed',
])

function money(value: unknown) {
  const number = Number(value || 0)
  return Number.isFinite(number) ? Math.round(number * 100) / 100 : 0
}

function metadataOf(value: unknown) {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? ({ ...(value as Record<string, unknown>) } as Record<string, unknown>)
    : {}
}

function hasManualQuoteFinancialOverride(
  reservation: ExistingReservation,
  key: 'quoteSoldPrice' | 'quoteDiscountTotal',
  currentValue: number,
) {
  const metadata = metadataOf(reservation.metadata)
  const previousQuoteValue = Number(metadata[key])
  return Number.isFinite(previousQuoteValue) && money(previousQuoteValue) !== money(currentValue)
}

function isOperationalReservation(reservation: ExistingReservation) {
  return Boolean(
    reservation.itemCount > 0 ||
    PROGRESSED_RESERVATION_STATUSES.has(reservation.status) ||
    money(reservation.booked_cost_total) > 0 ||
    money(reservation.supplier_refund_total) > 0 ||
    money(reservation.customer_refund_total) > 0 ||
    money(reservation.commission_expected_total) > 0 ||
    money(reservation.commission_received_total) > 0 ||
    reservation.supplier_reference ||
    reservation.booking_reference,
  )
}

function isAutoGeneratedReservation(reservation: ExistingReservation) {
  const metadata = metadataOf(reservation.metadata)
  return metadata.autoGenerated === true || metadata.source === 'final_quote_selection'
}

function matchesLegacyReservation(reservation: ExistingReservation, desired: DesiredReservation) {
  if (reservation.quote_id !== desired.quoteId) return false
  if (reservation.reservation_type !== desired.reservationType) return false
  const metadata = metadataOf(reservation.metadata)

  if (desired.syncKey === 'flight-main') {
    return metadata.flightPart !== 'linked_leg'
  }
  if (desired.syncKey.startsWith('flight-linked-')) {
    const linked = metadata.linkedFlightSelection as { groupId?: string } | undefined
    const desiredLinked = desired.metadata.linkedFlightSelection as { groupId?: string } | undefined
    return linked?.groupId === desiredLinked?.groupId
  }
  if (desired.syncKey.startsWith('hotel-')) {
    return metadata.stayGroupId === desired.metadata.stayGroupId
  }
  if (desired.syncKey.startsWith('visa-')) {
    return metadata.optionId === desired.metadata.optionId
  }
  if (desired.syncKey === 'transport-family-allocation' || desired.syncKey === 'transport') {
    return metadata.physicalReservation !== true
  }
  if (desired.syncKey === 'package-adjustment') {
    return metadata.adjustmentType === desired.metadata.adjustmentType
  }
  return false
}

function findReservationMatch(
  existing: ExistingReservation[],
  desired: DesiredReservation,
  usedIds: Set<string>,
) {
  const available = existing.filter(
    (reservation) => !usedIds.has(reservation.id) && isAutoGeneratedReservation(reservation),
  )
  const exactSyncKey = available.find((reservation) => {
    const metadata = metadataOf(reservation.metadata)
    return reservation.quote_id === desired.quoteId && metadata.syncKey === desired.syncKey
  })
  if (exactSyncKey) return exactSyncKey

  const exactSourceKey = available.find((reservation) => {
    const metadata = metadataOf(reservation.metadata)
    return reservation.quote_id === desired.quoteId && metadata.sourceKey === desired.sourceKey
  })
  return (
    exactSourceKey ||
    available.find((reservation) => matchesLegacyReservation(reservation, desired))
  )
}

function findPhysicalTransportMatch(existing: ExistingReservation[], usedIds: Set<string>) {
  return existing.find((reservation) => {
    const metadata = metadataOf(reservation.metadata)
    return (
      !usedIds.has(reservation.id) &&
      reservation.reservation_type === 'transport' &&
      metadata.physicalReservation === true
    )
  })
}

function quoteMetadata(existingMetadata: unknown, desired: DesiredReservation, syncedAt: string) {
  const metadata = metadataOf(existingMetadata)
  QUOTE_METADATA_KEYS.forEach((key) => delete metadata[key])
  return {
    ...metadata,
    ...desired.metadata,
    autoGenerated: true,
    source:
      desired.syncKey === 'transport-group-physical'
        ? 'final_quote_group_transport'
        : 'final_quote_selection',
    sourceKey: desired.sourceKey,
    syncKey: desired.syncKey,
    familyLabel: desired.familyLabel,
    quoteSoldPrice: desired.soldPriceTotal,
    quoteDiscountTotal: desired.discountTotal,
    quoteInternalNotes: desired.internalNotes,
    quoteSyncedAt: syncedAt,
  }
}

function buildDesiredReservations(snapshot: TravelPackageFolder['selected_quote_snapshot']): {
  desired: DesiredReservation[]
  families: PackageQuoteReservationFamily[]
} {
  const groupFamilies = snapshot.group?.families || []
  const families: PackageQuoteReservationFamily[] = groupFamilies.length
    ? groupFamilies.map((family) => ({
        quoteId: family.quoteId,
        groupMemberId: family.memberId,
        familyLabel: family.familyLabel,
        payload: normalizePackageQuotePayload(family.payload),
        combination: family.selection.combination,
      }))
    : snapshot.quote?.id && snapshot.payload && snapshot.selection
      ? [
          {
            quoteId: snapshot.quote.id,
            groupMemberId: null,
            familyLabel: null,
            payload: normalizePackageQuotePayload(snapshot.payload),
            combination: snapshot.selection.combination,
          },
        ]
      : []

  const physicalTransport =
    groupFamilies.length > 0 ? buildSharedGroupTransportDraft(families, snapshot.quote?.id) : null
  const desired: DesiredReservation[] = families.flatMap((family) =>
    buildPackageQuoteReservationDrafts({
      payload: family.payload,
      combination: family.combination,
      familyLabel: family.familyLabel,
      sharedGroupTransportAllocation: groupFamilies.length > 0,
    }).map((draft) => ({
      ...draft,
      quoteId: family.quoteId,
      groupMemberId: family.groupMemberId || null,
      familyLabel: family.familyLabel || null,
      currency: family.combination.currency,
      depositRequired: Boolean(family.payload.depositRequired),
      depositAmount: money(family.payload.depositAmount),
    })),
  )

  if (groupFamilies.length > 0) {
    if (physicalTransport) {
      desired.push({
        ...physicalTransport,
        quoteId: null,
        groupMemberId: null,
        familyLabel: null,
        currency: families[0]?.combination.currency || 'GBP',
        depositRequired: false,
        depositAmount: 0,
      })
    }
  }

  return { desired, families }
}

function buildAggregatePassengerSummary(families: PackageQuoteReservationFamily[]) {
  return families.reduce(
    (total, family) => {
      const summary = buildPassengerSummary(family.payload)
      total.adults += summary.adults
      total.childrenPaying += summary.childrenPaying
      total.childrenFree += summary.childrenFree
      total.infants += summary.infants
      total.totalPassengers += summary.totalPassengers
      total.hotelPayingGuests += summary.hotelPayingGuests
      total.servicePassengers += summary.servicePassengers
      return total
    },
    {
      adults: 0,
      childrenPaying: 0,
      childrenFree: 0,
      infants: 0,
      totalPassengers: 0,
      hotelPayingGuests: 0,
      servicePassengers: 0,
    },
  )
}

function buildRefundCredits(
  quotes: TravelPackageQuote[],
  families: PackageQuoteReservationFamily[],
) {
  return families.flatMap((family) => {
    const quote = quotes.find((candidate) => candidate.id === family.quoteId)
    if (!quote) return []
    return family.combination.appliedOffers
      .filter((offer) => getPackageQuoteDiscountType(offer) === 'refund_adjustment')
      .flatMap((offer) => {
        const amount = getPackageOfferDiscountTotal(offer, family.payload)
        return amount > 0 ? [{ quote, offer, amount: money(amount) }] : []
      })
  })
}

function allocateGroupPaymentBreakdown(
  entries: Array<{
    quoteId: string
    combination: PackageResolvedSelection['combination']
  }>,
  breakdown: Partial<PackagePaymentBreakdown> | null | undefined,
) {
  const allocations = new Map<string, PackagePaymentBreakdown>()
  if (!breakdown || entries.length === 0) return allocations
  const groupSubtotal = entries.reduce(
    (total, entry) => total + entry.combination.packageSubtotalPrice,
    0,
  )
  if (groupSubtotal <= 0) return allocations

  const methods: Array<keyof PackagePaymentBreakdown> = ['cash', 'bankTransfer', 'card']
  entries.forEach((entry) => allocations.set(entry.quoteId, { cash: 0, bankTransfer: 0, card: 0 }))
  methods.forEach((method) => {
    const methodTotal = money(breakdown[method])
    let allocated = 0
    entries.forEach((entry, index) => {
      const amount =
        index === entries.length - 1
          ? money(methodTotal - allocated)
          : money((methodTotal * entry.combination.packageSubtotalPrice) / groupSubtotal)
      allocations.get(entry.quoteId)![method] = amount
      allocated = money(allocated + amount)
    })
  })
  return allocations
}

function buildDesiredPaymentRequests(
  snapshot: TravelPackageFolder['selected_quote_snapshot'],
): DesiredPaymentRequest[] {
  const entries: Array<{
    quoteId: string
    groupMemberId: string | null
    familyLabel: string | null
    payload: ReturnType<typeof normalizePackageQuotePayload>
    selection: PackageResolvedSelection
  }> = snapshot.group?.families.length
    ? snapshot.group.families.map((family) => ({
        quoteId: family.quoteId,
        groupMemberId: family.memberId,
        familyLabel: family.familyLabel,
        payload: normalizePackageQuotePayload(family.payload),
        selection: family.selection,
      }))
    : snapshot.quote?.id && snapshot.payload && snapshot.selection
      ? [
          {
            quoteId: snapshot.quote.id,
            groupMemberId: null,
            familyLabel: null,
            payload: normalizePackageQuotePayload(snapshot.payload),
            selection: snapshot.selection,
          },
        ]
      : []
  const groupPaymentSelection = entries.find(
    (entry) => entry.selection.selection.paymentScope === 'group',
  )?.selection.selection
  const groupAllocations = allocateGroupPaymentBreakdown(
    entries.map((entry) => ({
      quoteId: entry.quoteId,
      combination: entry.selection.combination,
    })),
    groupPaymentSelection?.groupPaymentBreakdown,
  )

  return entries.flatMap<DesiredPaymentRequest>((entry) => {
    const { selection, combination } = entry.selection
    const paymentIntent = groupPaymentSelection?.paymentIntent || selection.paymentIntent
    if (paymentIntent === 'installment_request') return []

    if (paymentIntent === 'deposit_only') {
      const paymentMethod = selection.depositPaymentMethod || 'bank_transfer'
      const summary = getPackageDepositPaymentSummary(entry.payload, paymentMethod)
      if (summary.total <= 0) return []
      const methodLabel =
        paymentMethod === 'card'
          ? 'Credit Card'
          : paymentMethod === 'cash'
            ? 'Cash'
            : 'Bank Transfer'
      return [
        {
          quoteId: entry.quoteId,
          groupMemberId: entry.groupMemberId,
          familyLabel: entry.familyLabel,
          source: 'final_quote_deposit_request' as const,
          paymentType: 'deposit' as const,
          paymentMethod,
          amount: summary.total,
          currency: combination.currency,
          notes:
            summary.processingFee > 0
              ? `Customer chose to pay the minimum deposit by ${methodLabel}. Deposit is non-refundable and must be paid as one full deposit payment. Includes ${entry.payload.cardProcessingFeePercent}% Credit Card processing fee.`
              : `Customer chose to pay the minimum deposit by ${methodLabel}. Deposit is non-refundable and must be paid as one full deposit payment.`,
          metadata: {
            nonRefundable: true,
            depositPaymentMethod: paymentMethod,
            baseDepositAmount: summary.depositAmount,
            processingFeeTotal: summary.processingFee,
            processingFeePercent:
              paymentMethod === 'card' ? entry.payload.cardProcessingFeePercent : 0,
          },
        },
      ]
    }

    const breakdown =
      groupAllocations.get(entry.quoteId) ||
      selection.paymentBreakdown ||
      combination.paymentBreakdown
    if (!breakdown) return []
    const methods: Array<[keyof PackagePaymentBreakdown, DesiredPaymentRequest['paymentMethod']]> =
      [
        ['cash', 'cash'],
        ['bankTransfer', 'bank_transfer'],
        ['card', 'card'],
      ]
    return methods.flatMap(([key, paymentMethod]) => {
      const baseAmount = money(breakdown[key])
      const processingFee =
        paymentMethod === 'card'
          ? money((baseAmount * Number(entry.payload.cardProcessingFeePercent || 0)) / 100)
          : 0
      const amount = money(baseAmount + processingFee)
      if (amount <= 0) return []
      return [
        {
          quoteId: entry.quoteId,
          groupMemberId: entry.groupMemberId,
          familyLabel: entry.familyLabel,
          source: 'final_quote_payment_breakdown' as const,
          paymentType: 'payment' as const,
          paymentMethod,
          amount,
          currency: combination.currency,
          notes:
            'Customer requested this payment split during quotation finalisation. Agent must approve or override.',
          metadata: {
            baseAmount,
            processingFeeTotal: processingFee,
            processingFeePercent:
              paymentMethod === 'card' ? entry.payload.cardProcessingFeePercent : 0,
          },
        },
      ]
    })
  })
}

export async function syncConvertedPackageFromQuotes(
  supabase: SupabaseClient,
  options: {
    packageId: string
    actorId?: string | null
    triggerQuoteId?: string | null
    reason?: string
  },
): Promise<PackageQuoteSyncResult> {
  const syncedAt = new Date().toISOString()
  const { data: packageData, error: packageError } = await supabase
    .from('travel_packages')
    .select('*')
    .eq('id', options.packageId)
    .single()
  if (packageError || !packageData) {
    throw new Error(packageError?.message || 'Converted package folder was not found')
  }

  const packageFolder = packageData as unknown as TravelPackageFolder
  const { data: quoteData, error: quoteError } = await supabase
    .from('travel_package_quotes')
    .select('*')
    .eq('converted_package_id', options.packageId)
    .order('created_at', { ascending: true })
  if (quoteError || !quoteData?.length) {
    throw new Error(quoteError?.message || 'Converted package source quotations were not found')
  }
  const quotes = quoteData as unknown as TravelPackageQuote[]
  const refreshed = rebuildConvertedPackageSnapshotFromQuotes(
    quotes,
    packageFolder.selected_quote_snapshot,
  )
  const { desired, families } = buildDesiredReservations(refreshed.snapshot)

  const [
    { data: reservationData, error: reservationError },
    { data: itemData },
    { data: invoiceData },
    { data: paymentData },
  ] = await Promise.all([
    supabase.from('travel_package_reservations').select('*').eq('package_id', options.packageId),
    supabase
      .from('travel_package_reservation_items')
      .select('id, reservation_id')
      .eq('package_id', options.packageId),
    supabase
      .from('travel_package_invoices')
      .select('id, quote_id, status, released_to_customer')
      .eq('package_id', options.packageId)
      .neq('status', 'void'),
    supabase.from('travel_package_payments').select('*').eq('package_id', options.packageId),
  ])
  if (reservationError) throw new Error(reservationError.message)

  const itemCounts = new Map<string, number>()
  ;(itemData || []).forEach((item) => {
    itemCounts.set(item.reservation_id, (itemCounts.get(item.reservation_id) || 0) + 1)
  })
  const existing = ((reservationData || []) as unknown as TravelPackageReservation[]).map(
    (reservation) => ({
      ...reservation,
      itemCount: itemCounts.get(reservation.id) || 0,
    }),
  )
  const conflicts: SyncConflict[] = []
  const usedIds = new Set<string>()
  let createdReservations = 0
  let updatedReservations = 0
  let cancelledReservations = 0

  const legacySharedBookedCost = Math.max(
    0,
    ...existing
      .filter((reservation) => {
        return (
          reservation.reservation_type === 'transport' &&
          isAutoGeneratedReservation(reservation) &&
          money(reservation.booked_cost_total) > 0
        )
      })
      .map((reservation) => money(reservation.booked_cost_total)),
  )

  for (const desiredReservation of desired) {
    const isPhysicalTransport = desiredReservation.syncKey === 'transport-group-physical'
    const matched = isPhysicalTransport
      ? findPhysicalTransportMatch(existing, usedIds)
      : findReservationMatch(existing, desiredReservation, usedIds)

    if (!matched) {
      const bookedCost = isPhysicalTransport
        ? legacySharedBookedCost || desiredReservation.suggestedBookedCost
        : desiredReservation.suggestedBookedCost
      const { error } = await supabase.from('travel_package_reservations').insert({
        package_id: options.packageId,
        quote_id: desiredReservation.quoteId,
        group_member_id: desiredReservation.groupMemberId,
        created_by: options.actorId || packageFolder.created_by,
        updated_by: options.actorId || packageFolder.created_by,
        reservation_type: desiredReservation.reservationType,
        title: desiredReservation.title,
        status: 'reservation_pending',
        supplier_name:
          typeof desiredReservation.metadata.transportMainSupplierName === 'string'
            ? desiredReservation.metadata.transportMainSupplierName || null
            : null,
        currency: desiredReservation.currency,
        booked_cost_total: bookedCost,
        sold_price_total: desiredReservation.soldPriceTotal,
        discount_total: desiredReservation.discountTotal,
        commission_expected_total: 0,
        deposit_required: desiredReservation.depositRequired,
        deposit_amount: desiredReservation.depositAmount,
        payment_due_at: syncedAt,
        customer_visible: false,
        internal_notes: desiredReservation.internalNotes,
        metadata: quoteMetadata({}, desiredReservation, syncedAt),
      })
      if (error) throw new Error(error.message)
      createdReservations += 1
      continue
    }

    usedIds.add(matched.id)
    const preservePhysicalSoldOverride =
      isPhysicalTransport && metadataOf(matched.metadata).soldPriceOverride === true
    const preserveSold =
      preservePhysicalSoldOverride ||
      matched.itemCount > 0 ||
      hasManualQuoteFinancialOverride(matched, 'quoteSoldPrice', matched.sold_price_total)
    const preserveDiscount =
      matched.itemCount > 0 ||
      hasManualQuoteFinancialOverride(matched, 'quoteDiscountTotal', matched.discount_total)
    if (preserveSold || preserveDiscount) {
      conflicts.push({
        kind: 'reservation',
        objectId: matched.id,
        message: `${matched.title} has agent-entered financial values and was left for review.`,
      })
    }

    const nextBookedCost =
      desiredReservation.syncKey === 'transport-family-allocation'
        ? 0
        : isPhysicalTransport && legacySharedBookedCost > 0
          ? legacySharedBookedCost
          : money(matched.booked_cost_total) || desiredReservation.suggestedBookedCost
    const { error } = await supabase
      .from('travel_package_reservations')
      .update({
        quote_id: desiredReservation.quoteId,
        group_member_id: desiredReservation.groupMemberId,
        updated_by: options.actorId || packageFolder.created_by,
        reservation_type: desiredReservation.reservationType,
        title: desiredReservation.title,
        currency: desiredReservation.currency,
        booked_cost_total: nextBookedCost,
        sold_price_total: preserveSold
          ? matched.sold_price_total
          : desiredReservation.soldPriceTotal,
        discount_total: preserveDiscount
          ? matched.discount_total
          : desiredReservation.discountTotal,
        deposit_required: desiredReservation.depositRequired,
        deposit_amount: desiredReservation.depositAmount,
        internal_notes: desiredReservation.internalNotes,
        metadata: {
          ...quoteMetadata(matched.metadata, desiredReservation, syncedAt),
          ...(isPhysicalTransport
            ? {
                soldPriceOverride: preservePhysicalSoldOverride,
                derivedSoldPrice: desiredReservation.soldPriceTotal,
              }
            : {}),
        },
      })
      .eq('id', matched.id)
      .eq('package_id', options.packageId)
    if (error) throw new Error(error.message)
    updatedReservations += 1
  }

  for (const reservation of existing) {
    if (usedIds.has(reservation.id) || !isAutoGeneratedReservation(reservation)) continue
    if (isOperationalReservation(reservation)) {
      conflicts.push({
        kind: 'reservation',
        objectId: reservation.id,
        message: `${reservation.title} is no longer in the quotation but has operational data, so it was retained.`,
      })
      continue
    }
    const metadata = metadataOf(reservation.metadata)
    const { error } = await supabase
      .from('travel_package_reservations')
      .update({
        status: 'cancelled',
        sold_price_total: 0,
        discount_total: 0,
        cancelled_at: syncedAt,
        updated_by: options.actorId || packageFolder.created_by,
        metadata: {
          ...metadata,
          quoteSyncRemoved: true,
          quoteSyncRemovedAt: syncedAt,
        },
      })
      .eq('id', reservation.id)
      .eq('package_id', options.packageId)
    if (error) throw new Error(error.message)
    cancelledReservations += 1
  }

  let updatedCredits = 0
  let createdPaymentRequests = 0
  let updatedPaymentRequests = 0
  let cancelledPaymentRequests = 0
  const desiredCredits = buildRefundCredits(quotes, families)
  const existingPayments = (paymentData || []) as Array<Record<string, unknown>>
  const matchedCreditIds = new Set<string>()
  for (const credit of desiredCredits) {
    const matched = existingPayments.find((payment) => {
      const metadata = metadataOf(payment.metadata)
      return (
        payment.payment_type === 'account_credit' &&
        !matchedCreditIds.has(String(payment.id)) &&
        (metadata.offerId === credit.offer.id ||
          (metadata.quoteId === credit.quote.id &&
            payment.receipt_reference ===
              (credit.offer.reference || credit.offer.title || credit.quote.title)))
      )
    })
    if (matched) {
      matchedCreditIds.add(String(matched.id))
      const family = families.find((entry) => entry.quoteId === credit.quote.id)
      const { error } = await supabase
        .from('travel_package_payments')
        .update({
          quote_id: credit.quote.id,
          group_member_id: family?.groupMemberId || null,
          amount: credit.amount,
          currency: credit.quote.currency,
          receipt_reference: credit.offer.reference || credit.offer.title || credit.quote.title,
          notes: credit.offer.summary || 'Credit transferred from a previous package refund.',
          updated_by: options.actorId || packageFolder.created_by,
          metadata: {
            ...metadataOf(matched.metadata),
            autoGenerated: true,
            source: 'previous_refund_reimbursement',
            quoteId: credit.quote.id,
            offerId: credit.offer.id,
            adjustmentTitle: credit.offer.title,
            quoteSyncedAt: syncedAt,
          },
        })
        .eq('id', matched.id)
        .eq('package_id', options.packageId)
      if (error) throw new Error(error.message)
      updatedCredits += 1
      continue
    }

    const family = families.find((entry) => entry.quoteId === credit.quote.id)
    const { error } = await supabase.from('travel_package_payments').insert({
      package_id: options.packageId,
      quote_id: credit.quote.id,
      group_member_id: family?.groupMemberId || null,
      amount: credit.amount,
      currency: credit.quote.currency,
      payment_type: 'account_credit',
      payment_method: 'other',
      payment_status: 'completed',
      requested_at: syncedAt,
      received_at: syncedAt,
      receipt_reference: credit.offer.reference || credit.offer.title || credit.quote.title,
      notes: credit.offer.summary || 'Credit transferred from a previous package refund.',
      metadata: {
        autoGenerated: true,
        source: 'previous_refund_reimbursement',
        quoteId: credit.quote.id,
        familyLabel: family?.familyLabel || null,
        offerId: credit.offer.id,
        adjustmentTitle: credit.offer.title,
        quoteSyncedAt: syncedAt,
      },
      created_by: options.actorId || packageFolder.created_by,
      updated_by: options.actorId || packageFolder.created_by,
    })
    if (error) throw new Error(error.message)
    updatedCredits += 1
  }

  existingPayments.forEach((payment) => {
    const metadata = metadataOf(payment.metadata)
    if (
      payment.payment_type === 'account_credit' &&
      metadata.source === 'previous_refund_reimbursement' &&
      !matchedCreditIds.has(String(payment.id))
    ) {
      conflicts.push({
        kind: 'payment',
        objectId: String(payment.id),
        message:
          'A completed previous-refund credit is no longer in the quotation and was retained for financial review.',
      })
    }
  })

  const desiredPaymentRequests = buildDesiredPaymentRequests(refreshed.snapshot)
  const usedPaymentRequestIds = new Set<string>()
  for (const desiredRequest of desiredPaymentRequests) {
    const matched = existingPayments.find((payment) => {
      const metadata = metadataOf(payment.metadata)
      return (
        !usedPaymentRequestIds.has(String(payment.id)) &&
        metadata.autoGenerated === true &&
        metadata.source === desiredRequest.source &&
        (payment.quote_id === desiredRequest.quoteId ||
          metadata.quoteId === desiredRequest.quoteId) &&
        payment.payment_method === desiredRequest.paymentMethod
      )
    })

    if (matched) {
      usedPaymentRequestIds.add(String(matched.id))
      if (matched.payment_status !== 'pending' || matched.received_at) {
        conflicts.push({
          kind: 'payment',
          objectId: String(matched.id),
          message:
            'A progressed payment was preserved and must be reviewed against the revised quotation balance.',
        })
        continue
      }
      const { error } = await supabase
        .from('travel_package_payments')
        .update({
          quote_id: desiredRequest.quoteId,
          group_member_id: desiredRequest.groupMemberId,
          amount: desiredRequest.amount,
          currency: desiredRequest.currency,
          payment_type: desiredRequest.paymentType,
          payment_method: desiredRequest.paymentMethod,
          due_at: syncedAt,
          notes: desiredRequest.notes,
          updated_by: options.actorId || packageFolder.created_by,
          metadata: {
            ...metadataOf(matched.metadata),
            ...desiredRequest.metadata,
            autoGenerated: true,
            source: desiredRequest.source,
            quoteId: desiredRequest.quoteId,
            familyLabel: desiredRequest.familyLabel,
            quoteSyncedAt: syncedAt,
          },
        })
        .eq('id', matched.id)
        .eq('package_id', options.packageId)
      if (error) throw new Error(error.message)
      updatedPaymentRequests += 1
      continue
    }

    const { error } = await supabase.from('travel_package_payments').insert({
      package_id: options.packageId,
      quote_id: desiredRequest.quoteId,
      group_member_id: desiredRequest.groupMemberId,
      amount: desiredRequest.amount,
      currency: desiredRequest.currency,
      payment_type: desiredRequest.paymentType,
      payment_method: desiredRequest.paymentMethod,
      payment_status: 'pending',
      requested_at: syncedAt,
      due_at: syncedAt,
      notes: desiredRequest.notes,
      metadata: {
        ...desiredRequest.metadata,
        autoGenerated: true,
        source: desiredRequest.source,
        quoteId: desiredRequest.quoteId,
        familyLabel: desiredRequest.familyLabel,
        quoteSyncedAt: syncedAt,
      },
      created_by: options.actorId || packageFolder.created_by,
      updated_by: options.actorId || packageFolder.created_by,
    })
    if (error) throw new Error(error.message)
    createdPaymentRequests += 1
  }

  for (const payment of existingPayments) {
    const metadata = metadataOf(payment.metadata)
    if (
      metadata.autoGenerated !== true ||
      !['final_quote_deposit_request', 'final_quote_payment_breakdown'].includes(
        String(metadata.source),
      ) ||
      usedPaymentRequestIds.has(String(payment.id)) ||
      ['cancelled', 'failed', 'refunded'].includes(String(payment.payment_status))
    ) {
      continue
    }
    if (payment.payment_status !== 'pending' || payment.received_at) {
      conflicts.push({
        kind: 'payment',
        objectId: String(payment.id),
        message:
          'A progressed payment no longer matches the quotation and was retained for financial review.',
      })
      continue
    }
    const { error } = await supabase
      .from('travel_package_payments')
      .update({
        payment_status: 'cancelled',
        updated_by: options.actorId || packageFolder.created_by,
        metadata: {
          ...metadata,
          quoteSyncRemoved: true,
          quoteSyncRemovedAt: syncedAt,
        },
      })
      .eq('id', payment.id)
      .eq('package_id', options.packageId)
    if (error) throw new Error(error.message)
    cancelledPaymentRequests += 1
  }
  ;(invoiceData || []).forEach((invoice) => {
    conflicts.push({
      kind: 'invoice',
      objectId: invoice.id,
      message: invoice.released_to_customer
        ? 'A released invoice requires an amendment after this quotation change.'
        : 'The draft invoice must be regenerated or reviewed after this quotation change.',
    })
  })

  if (refreshed.snapshot.group?.families.length && packageFolder.group_id) {
    for (const family of refreshed.snapshot.group.families) {
      const { error } = await supabase
        .from('travel_package_group_members')
        .update({ package_id: options.packageId })
        .eq('id', family.memberId)
        .eq('group_id', packageFolder.group_id)
      if (error) {
        conflicts.push({
          kind: 'group_member',
          objectId: family.memberId,
          message: `The ${family.familyLabel} group link could not be repaired: ${error.message}`,
        })
      }
    }
  }

  const leadPayload = normalizePackageQuotePayload(refreshed.snapshot.payload)
  const syncStatus = conflicts.length > 0 ? 'review_required' : 'synced'
  const previousMetadata = metadataOf(packageFolder.metadata)
  const nextMetadata = {
    ...previousMetadata,
    quoteSync: {
      status: syncStatus,
      syncedAt,
      triggerQuoteId: options.triggerQuoteId || null,
      quoteIds: quotes.map((quote) => quote.id),
      createdReservations,
      updatedReservations,
      cancelledReservations,
      updatedCredits,
      createdPaymentRequests,
      updatedPaymentRequests,
      cancelledPaymentRequests,
      invoiceReviewRequired: conflicts.some((conflict) => conflict.kind === 'invoice'),
      conflicts,
    },
  }
  const { error: packageUpdateError } = await supabase
    .from('travel_packages')
    .update({
      customer_name:
        refreshed.snapshot.selection?.selection.customerName ||
        refreshed.snapshot.quote?.customer_name ||
        leadPayload.customerName ||
        packageFolder.customer_name,
      customer_phone:
        refreshed.snapshot.selection?.selection.customerPhone ||
        refreshed.snapshot.quote?.customer_phone ||
        leadPayload.customerPhone ||
        packageFolder.customer_phone,
      customer_email:
        refreshed.snapshot.selection?.selection.customerEmail ||
        refreshed.snapshot.quote?.customer_email ||
        leadPayload.customerEmail ||
        packageFolder.customer_email,
      package_type: leadPayload.packageType,
      departure_date: leadPayload.departureDate || null,
      return_date: leadPayload.returnDate || null,
      passenger_summary: buildAggregatePassengerSummary(families),
      selected_quote_snapshot: refreshed.snapshot,
      current_public_summary: refreshed.publicSummary,
      metadata: nextMetadata,
    })
    .eq('id', options.packageId)
  if (packageUpdateError) throw new Error(packageUpdateError.message)

  await syncPackagePaymentFinancials(supabase, options.packageId)

  if (options.triggerQuoteId) {
    const { data: versionData } = await supabase
      .from('travel_package_versions')
      .select('version_number')
      .eq('object_type', 'selected_quote')
      .eq('object_id', options.triggerQuoteId)
      .order('version_number', { ascending: false })
      .limit(1)
      .maybeSingle()
    const triggerQuote = quotes.find((quote) => quote.id === options.triggerQuoteId)
    if (triggerQuote) {
      await supabase.from('travel_package_versions').insert({
        package_id: options.packageId,
        quote_id: triggerQuote.id,
        object_type: 'selected_quote',
        object_id: triggerQuote.id,
        version_number: Number(versionData?.version_number || 0) + 1,
        visibility: 'internal_only',
        snapshot:
          refreshed.snapshot.group?.families.find((family) => family.quoteId === triggerQuote.id) ||
          refreshed.snapshot,
        internal_change_summary:
          options.reason || 'Quotation and package operations reconciled after a quote edit.',
        created_by: options.actorId || packageFolder.created_by,
      })
    }
  }

  await recordPackageAuditEvent(
    supabase as unknown as Parameters<typeof recordPackageAuditEvent>[0],
    {
      packageId: options.packageId,
      quoteId: options.triggerQuoteId,
      actorId: options.actorId,
      eventType: 'package_quote_reconciled',
      eventSummary:
        syncStatus === 'synced'
          ? 'Converted package reconciled with its current source quotation.'
          : 'Converted package reconciled with its current source quotation and flagged for review.',
      beforeData: packageFolder.selected_quote_snapshot,
      afterData: refreshed.snapshot,
      metadata: {
        status: syncStatus,
        createdReservations,
        updatedReservations,
        cancelledReservations,
        updatedCredits,
        createdPaymentRequests,
        updatedPaymentRequests,
        cancelledPaymentRequests,
        conflicts,
      },
    },
  )

  return {
    packageId: options.packageId,
    quoteIds: quotes.map((quote) => quote.id),
    status: syncStatus,
    createdReservations,
    updatedReservations,
    cancelledReservations,
    updatedCredits,
    createdPaymentRequests,
    updatedPaymentRequests,
    cancelledPaymentRequests,
    conflicts,
    snapshot: refreshed.snapshot,
  }
}
